-- Create CUSTOMERS table
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    EMAIL_ADDRESS VARCHAR2(255 CHAR),
    FULL_NAME VARCHAR2(255 CHAR)
);

-- Create STORES table
CREATE TABLE STORES (
    STORE_ID NUMBER PRIMARY KEY,
    STORE_NAME VARCHAR2(255 CHAR),
    WEB_ADDRESS VARCHAR2(100 CHAR),
    PHYSICAL_ADDRESS VARCHAR2(255 CHAR),
    LATITUDE NUMBER,
    LONGITUDE NUMBER,
    LOGO BLOB,
    LOGO_MIME_TYPE VARCHAR2(512 CHAR),
    LOGO_FILENAME VARCHAR2(512 CHAR),
    LOGO_CHARSET VARCHAR2(512 CHAR),
    LOGO_LAST_UPDATED DATE
);

-- Create PRODUCTS table
CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(255 CHAR),
    UNIT_PRICE NUMBER(10,2),
    PRODUCT_DETAILS BLOB,
    PRODUCT_IMAGE BLOB,
    IMAGE_FILENAME VARCHAR2(512 CHAR),
    IMAGE_CHARSET VARCHAR2(512 CHAR),
    IMAGE_MIME_TYPE VARCHAR2(512 CHAR),
    IMAGE_LAST_UPDATED DATE
);

-- Create ORDERS table
CREATE TABLE ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    ORDER_DATETIME TIMESTAMP(6),
    CUSTOMER_ID NUMBER,
    STORE_ID NUMBER,
    ORDER_STATUS VARCHAR2(10 CHAR),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (STORE_ID) REFERENCES STORES(STORE_ID)
);

-- Create ORDER_ITEMS table
CREATE TABLE ORDER_ITEMS (
    ORDER_ID NUMBER,
    LINE_ITEM NUMBER,
    PRODUCT_ID NUMBER,
    UNIT_PRICE NUMBER(10,2),
    QUANTITY NUMBER,
    PRIMARY KEY (ORDER_ID, LINE_ITEM),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);


ALTER TABLE PRODUCTS
DROP COLUMN PRODUCT_DETAILS;

ALTER TABLE PRODUCTS
ADD (PRODUCT_DETAILS VARCHAR2(4000 CHAR));